### ISSUE TITLE
> Hi. You are correct, it refers to the number of pole pairs in the motors. The name seems to be stupid.. :)

### ISSUE THREAD

**Issue by y5664579** [pekkaroi/bldc-drive#15]
> Hi. You are correct, it refers to the number of pole pairs in the motors. The name seems to be stupid.. :)

------
So encoder_poles = all coils / 3
Is it right?
BTW what does commutation_offset mean?
thx for your reply.

_Originally posted by @y5664579 in https://github.com/pekkaroi/bldc-drive/issues/14#issuecomment-846818567_

**Comment by pekkaroi** [comment]
Hi. Sorry for not replying earlier, I am not very active in github nowadays.. If I remember correctly, with commutation_offset you can modify the position where the commutation happens, when using encoder and not hall sensors.
