### ISSUE TITLE
Dead time

### ISSUE THREAD

**Issue by lonelymyp** [pekkaroi/bldc-drive#4]
I want to customize the firmware, for my motor control board, where can I configure the deadtime?

**Comment by pekkaroi** [comment]
Hi, It is defined in pwm.h, the parameter BLDC_NOL (non-overlapping time)

**Comment by lonelymyp** [comment]
Thank you.
and how this relates to stm32f10x_tim.c   TIM_BDTRInitStruct->TIM_DeadTime = 0x00;

**Comment by pekkaroi** [comment]
in the pwm.c initialization, the TIM_DeadTime is set:
TIM_BDTRInitStructure.TIM_DeadTime = BLDC_NOL;
